2024-08-09 10:29:07,740 ERROR: Unhandled Exception: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66b5a19e99d5a445f8351eff, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> [in C:\New Project\proj\fucy_fullstack_project\backend\app\__init__.py:46]
Traceback (most recent call last):
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New Project\proj\fucy_fullstack_project\backend\app\routes.py", line 98, in sideBarNode
    data = list(db.side_bar_nodes.find({}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
      ^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
           ^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91770\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66b5a19e99d5a445f8351eff, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
